spring:
  datasource:
    url: jdbc:sqlserver://azure-sqlserver-server.database.windows.net:1433;database=azure-sqlserver;user=achyu@azure-sqlserver-server;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: achyu
    password: Pani@1234
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port:9191


